### PR TITLE
Fix bug: Wrong UI display after executing commands

### LINKED ISSUE #121: [PE-D][Tester D] List of contacts in the module page changes to list all contacts instead of just contacts with association to module when adding new person
Step 1. First, I did the command `goto CS2103T`. 

Step 2. Next, I did the command `add-person n/John Deep e/johnd@example.com p/98765432`.

This is the current state of the application:

This causes the page to be updated to this:
.

What I would expect as a user is that the contact list either stays the same or I get redirected back to the home page. This might be confusing to users as they might think that all the users shown are contacts in the module as well.

Suggestion: 
Perhaps, there could be a way to add a contact directly into a module instead of making an association after adding a contact into the application then making the association.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: leongdl135/ped#1

### PR DESCRIPTION
**Pull request by ekweirui**
Currently after executing certain commands, the UI displayed list is not updated instantly, and this was the source of many bugs in the PE dry run.

This needs to be changed to lower our bug count and increase ease of use for users.

List of commands that this pull request changes and their new behavior:
* `AddModuleCommand` -> new behavior: After adding a module, goes to home page
* `AddPersonCommand` -> new behavior: After adding a person, goes to home page.
* `DeleteModuleCommand` -> new behavior: After deleting a module, goes to home page.
* `EditModuleCommand` -> new behavior: After editing a module, goes to home page.
* `EditPersonCommand` -> new behavior: After editing a person, goes to home page.

Resolves #121, #126, #139.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditModuleCommand.java [hunk 1]
```diff
@@ -71,7 +71,6 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         model.setModule(moduleToEdit, editedModule);
-        model.updateFilteredModuleList(PREDICATE_SHOW_ALL_MODULES);
```
Comment (Tan-Jia-Rong) [inline src/main/java/seedu/address/logic/commands/EditModuleCommand.java:74]: new behavior: After editing a module, the edited module itself shows changes, but no other changes to any of the displayed lists in UI.

Noticed that changing the module results in an empty module list but contact list remain unchanged atm.

I understand this is a draft pr but I think that it would be a reasonable expectation to see the editted module after editing. 

Hence I suggest that we update the UI to display the edited module

**Comment by cheeheng** [comment]
Resolves #121, resolves #129, resolves #139

File: src/main/java/seedu/address/logic/commands/EditModuleCommand.java (hunk 1 above)
Comment (ekweirui) [reply src/main/java/seedu/address/logic/commands/EditModuleCommand.java:74]: I have tried to reproduce the bug you mentioned but could not do so.
Perhaps you could try and see if you can reproduce the bug again?

**Comment by cheeheng** [comment]
Is there a reason why `delete-person` was not changed? It feels inconsistent with `add-person`, `add-module` and `delete-module`

**Review by teoyuqi — APPROVED** [review]
LGTM

**Review by cheeheng — APPROVED** [review]
LGTM
